### ISSUE TITLE
Install Fails

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#10]
**Describe the bug**
The installation from the system manifest URL fails.

**To Reproduce**
1. Go to the link here: 'https://github.com/thehappyanarchist/foundryacks'
2. Scroll down to the bottom of the page and copy the Manifest URL
3. Paste the Manifest URL into the available field on the Install System dialogue in Foundry
4. Click on the 'Install System' button on the Install System dialogue
5. See error 'Installation failed: invalid comment length. expected: 3. found:0

**Expected behavior**
The install of the System should execute and complete successfully

**Screenshots**
<img width="651" alt="Screenshot (150)" src="https://user-images.githubusercontent.com/48965463/94101987-0e805280-fdff-11ea-8541-f0828ecffa85.png">

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Browser: Brave
 - Version: 0.6.6

**Comment by thehappyanarchist** [comment]
Huh.... I just tested this yesterday. Let me uninstall and try to reinstall.

**Comment by thehappyanarchist** [comment]
In the mean time, you can manually install it just by extracting the zip file into the Systems subfolder.

**Comment by thehappyanarchist** [comment]
Okay, fixed the deployment zip. Something was off about it. Tested working fine now. Sorry for the inconvenience!
