### ISSUE TITLE
Option for Wisdom modifier to add to all Saves

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#11]
**Is your feature request related to a problem? Please describe.**
Wisdom modifier currently adds only to Saving Throws versus magic, however, one of the more common ACKS houserules is to simply apply the Wisdom modifier to all Saving Throws, bringing Wisdom more in line with the other attributes.

**Describe the solution you'd like**
A checkbox under System Settings to enable the optional rule of applying the Wisdom modifier to all Saves. When this option is set, the button for "vs Magic" on the Saving Throw pop-up dialog can be removed.

**Comment by thehappyanarchist** [comment]
Saves are not auto-calculated (there is no way to determine class of the PC), so literally this would just be a setting to remove the "vs Magic" button on the pop-up? What about the Bonus vs Magic field on the sheet? That too?

**Comment by thehappyanarchist** [comment]
Okay, I've finished this change. I'm removing both the bonus vs magic field and the button when you check the box. Let's keep the houserules to a minimum tho, I realize this is a popular one, but I don't want to clutter the settings menu.
