### ISSUE TITLE
HD rolls need a floor set

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#12]
**Is your feature request related to a problem? Please describe.**
When rolling for HD, the Constitution modifier is applied to the roll. However, on a Character with a negative Constitution modifier this can result in a negative hp roll.

**Describe the solution you'd like**
Clamp the result of a HD roll to a minimum of 1.

**Comment by thehappyanarchist** [comment]
Resolved. Will be fixed in release 0.5.1.
