### ISSUE TITLE
Damage rolls need a floor set

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#13]
**Is your feature request related to a problem? Please describe.**
When rolling for weapon damage, the Strength (or other) modifier is applied to the roll. However, on a Character with a negative Strength modifier this can result in a negative Damage roll.

**Expected behavior**
Damage rolls should produce a minimum of 1 point of damage. Clamp the result of a Damage roll to a minimum of 1.

**Comment by thehappyanarchist** [comment]
Fixed. Will be added to release 0.5.1.
