### ISSUE TITLE
Set core rule option to always miss on a 1, always hit on a critical.

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#14]
**Is your feature request related to a problem? Please describe.**
I am uncertain, as this is not something I use in my home game, but it appears you have implemented exploding d20s for Attack Throws on a natural 20; this is perhaps in line with HFH, but is not core ACKS.

**Describe the solution you'd like**
A checkbox under System Settings to enable the optional rule of exploding d20s on a natural 20 for Attack Throws. Set the default behaviour to a natural 20 on an Attack Throw to be merely an automatic hit.

**Additional context**
<img width="224" alt="Screenshot (151)" src="https://user-images.githubusercontent.com/48965463/94159848-07cefb00-fe52-11ea-94f4-7c11186dd2de.png">

**Comment by thehappyanarchist** [comment]
Added to 0.5.1 deployment.

**Comment by thehappyanarchist** [comment]
Leaving this open until I release the automatic hit and miss.

**Comment by thehappyanarchist** [comment]
Okay, put this in. Enjoy your boring core rules...
