### ISSUE TITLE
Morale follows the OSE standard

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#16]
**Is your feature request related to a problem? Please describe.**
Morale is currently listed as a target value for a Morale Roll, per OSE rules.

**Describe the solution you'd like**
Change to a Morale bonus (e.g. +2, -1, 0, etc.) that is applied to a Morale Roll, per ACKS core rules.

**Comment by thehappyanarchist** [comment]
Fixed in THA-Dev branch. Will push to master on next release once I hear back from the author on RAW for loyalty checks.
