### ISSUE TITLE
Setting the "Retainer" tweak doesn't add Morale and Loyalty values

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#17]
**Is your feature request related to a problem? Please describe.**
Retainers have both Morale ratings and Loyalty ratings, expressed as + or - numeric values. When a Character is set as a Retainer under Tweaks, there is nowhere on the sheet to record or roll against these values.

**Describe the solution you'd like**
Find a spot to add a Morale and Loyalty fields with roll icons to the Character sheet when the Retainer checkbox is selected under Tweaks.

**Comment by thehappyanarchist** [comment]
I'll tackle this next.

**Comment by thehappyanarchist** [comment]
Implemented a temporary solution to THA-Dev branch. Waiting on the author to confirm RAW before pushing to master and release. For now, ACKS morale and loyalty checks can be triggered by clicking on the relevant fields.
