### ISSUE TITLE
Apply ACKS Repertoire rules

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#18]
**Is your feature request related to a problem? Please describe.**
The Spells tab of the Sheet currently has a value for Memorized spells, per OSE rules, and doesn't follow the rules for Repertoires of ACKS core. 

**Describe the solution you'd like**
Remove the Memorized field from spells, and change the Spells Cast field to a positive value. Once the rollup of Spells Cast value of a given level equals the Spell Slots for that level of spells, prevent the "casting" of additional spells (either by the roll icon, or the eye icon), and post an error message to all users: "{character name} has no further {spell level} spell slots today!" or something similar.

**Comment by thehappyanarchist** [comment]
I've implemented this in 0.6.1 except for the posting of the message, which I think might be too much automation? IMO, the player should be able to track his own spells on his sheet the same as if it were on paper in front of him, and there are AXIOMS rules for players to overcast, so I wouldn't want to prevent that. I'm open to discussion about it for sure tho, so I will reopen the issue if needed.
