### ISSUE TITLE
The Reset Spell Slots button doesn't reset the Spell Slot values

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#19]
**Describe the bug**
When clicking on the Reset Spell Slots button on the Spells tab, the Spells Cast field briefly flickers, but retains its current value (e.g. -1) instead of resetting to 0.

**To Reproduce**
1. Create a Spell Item.
2. Put it on a Character Sheet
3. Click on the Spell Item icon on the Spells tab, or the eye icon under the Spell Item on the Spells tab; the Spells Cast field should change to -1
4. Click on the Reset Spell slots button; the Spells Cast field briefly flickers, but retains its current value (e.g. -1)

**Expected behavior**
Clicking on the Reset Spell slots button should reset all Spells Cast fields to a value of 0.

**Additional context**
This was a known issue in the OSE System for Monster Weapon attacks; when the Reset all Attacks per Round button was clicked, it did not correctly reset the Attacks Spent This Round field on all Monster Weapons. Presumably the code is similar, although I haven't looked at it, as U-man fixed it immediately.

**Comment by thehappyanarchist** [comment]
I just tried and I can't reproduce this in my own game. It seems to be working fine.

It's odd, since we're actively playing and my players use it every session, and I know I use it every round for monster attacks.

**Comment by Bobloblah** [comment]
As I think I mentioned, I had seen this bug previously in the OSE System. Maybe it's a holdover on old characters? I'll do some more testing.

**Comment by thehappyanarchist** [comment]
Was never able to reproduce on my end, and we've since revised the spell system as well. We can always reopen this issue once it's reliably reproducable.
