### ISSUE TITLE
Add an Apply 1/2 Damage option to the pop-up

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#20]
**Is your feature request related to a problem? Please describe.**
Currently, when right-clicking on a rolled damage value on a Chat Card, a small pop-up menu appears offering the option to apply the rolled value, either as damage or healing, to a selected Actor. Applying half damage is an extremely common operation in ACKS, either due to a successful Saving Throw or in-built resistances possessed by certain monsters.

**Describe the solution you'd like**
Add an option to the pop-up menu, "Apply 1/2 Damage", to halve the rolled damage, rounded up, before applying it to the selected actor.

**Comment by thehappyanarchist** [comment]
Added to 0.7.0
