### ISSUE TITLE
Add a Saving Throw Modifier

### ISSUE THREAD

**Issue by Bobloblah** [thehappyanarchist/foundryacks#30]
**Is your feature request related to a problem? Please describe.**
There is currently no way to add a general modifier to all saving throws without individually modifying each saving throw value.

**Describe the solution you'd like**
The ability to add a general saving throw modifier on the Tweaks pop-up that affects all Saving Throws.

**Additional context**
This is useful for Rings or Cloaks of Protection, as well as Proficiencies like Divine Blessing.

**Comment by thehappyanarchist** [comment]
This should be a relatively easy add to the Tweaks dialog. I'll put it in the next revision.

**Comment by thehappyanarchist** [comment]
Added to 0.7.0
